apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "blob.fullname" . }}
  labels:
    app: {{ template "blob.name" . }}
    chart: {{ template "blob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "blob.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "blob.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: blob-volume
          persistentVolumeClaim:
            claimName: blob-volume-claim
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 1516
              protocol: TCP
          volumeMounts:
            - mountPath: /opt
              name: blob-volume
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
