apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  commonName: agile-devops.club 
  dnsNames:
  - agile-devops.club
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: ingress-cert

