apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-denny
  labels:
    app: wordpress-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.8-apache
        env:
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_HOST
            value: mysql-service-denny:3306
          - name: WORDPRESS_DB_PASSWORD
            value: alfabeta
        ports:
        - name: http-port
          containerPort: 80

          
